### PR TITLE
Constrain to SilverStripe >=3.1,<4

### PR DESCRIPTION
**Pull request by Zauberfisch**

### CODE REVIEW

**Comment by Firesphere** [comment]
Seems good to me. @axyr ?

**Comment by Firesphere** [comment]
This would be better to be a `^3.1` constraint?

**Comment by Zauberfisch** [comment]
@Firesphere look at the commit, it actualy is. I just used >< as issue title for those who don't know what ^ does.

**Comment by Firesphere** [comment]
@Zauberfisch I know :) I just wanted to make sure you actually meant it like that instead of using the upper constraint method ;)

**Comment by Zauberfisch** [comment]
I am not quiet sure what you are trying to say. Both methods will yield exactly the same result, therefore it's not actually relevant which you would use.

**Comment by Firesphere** [comment]
I'm saying I wanted to make sure you decided to go with the `> <` on purpose

**Pull request merged**
